### ISSUE TITLE
Data Visualization

### ISSUE THREAD

**Issue by gdjmck** [tsinghua-fib-lab/UrbanKG-KnowSite#1]
Wonder how could I visualize the region and POI venue, can't read anything from the source data.

**Comment by liuyuaa** [comment]
Hi, we train the proposed model on the extracted KGs for Beijing and Shanghai without directly using the location information of POIs and regions. We just use location information for building the KGs, however, we cannot provide the raw data for now. 
If you'd like to visualize region and POI in an UrbanKG, I recommend you use the UrbanKG for New York, which can be found at        [KGSocio](https://github.com/tsinghua-fib-lab/KG-socioeconomic-indicator-prediction) or [KnowCL](https://github.com/tsinghua-fib-lab/UrbanKG-KnowCL). Based on POI ID and Region ID therein, you may need to further map with SafeGraph data for location information. Thanks.
